extension_dir = "C:/php_ext"
extension=php_fileinfo.dll
extension=php_gd.dll
extension=php_exif.dll
extension=php_mbstring.dll
extension=php_openssl.dll

display_errors = Off
log_errors = On
max_execution_time = 30
memory_limit = 128M
upload_max_filesize = 10M
post_max_size = 10M
